### ISSUE TITLE
How to use reasoning tokens

### ISSUE THREAD

**Issue by wiiiktor** [teticio/llama-squad#12]
Can you please elaborate more on this?: "We also found that the reasoning tokens allowed us to better retain the ability of the model to give an explanation for its response (by simply not including these tokens in the follow-up questions)"

**Comment by Deep1994** [comment]
Hi, do you have any idea about this? I also want to know how to achieve this. Thank you!

**Comment by teticio** [comment]
Without them, the model was forced to spit out the answer and I found that it could overfit and lose the ability to give a good explanation because it was so conidtioned to return a JSON answer. The reasoning tokens are a way of conditioning it so that it only returns JSON answers when preceded by them. But this is just a subjective observation.

**Comment by teticio** [comment]
@Deep1994 Are you not able to run the script with the setting for number of reasoning tokens?
